Tests and extra
assafYossef/AdvancedAlgebra pull request #9
Opened 2024-04-10 20:52 UTC by assafYossef

2024-04-10 21:04 UTC, idonahum1 commented
Don't add all the sphinx files, you can delete
_build folder under docs.

2024-04-11 09:05 UTC, idonahum1 requested changes
כל הכבוד :) תסתכל על ההערות שלי ותגיד מה דעתך

2024-04-11 09:05 UTC, idonahum1 commented on docs/_build/doctrees/galwa.doctree
אין צורך בקצבי _build של ספינקס.

2024-04-11 09:05 UTC, idonahum1 commented on docs/conf.py
זה בסדר, אבל כל מה שנמצא בתיקיית _build צריך להעיף

2024-04-11 09:05 UTC, idonahum1 commented on galwa/fields.py
> +        for i in range(1, int(math.sqrt(field_size)) + 1):
אפשר להשתמש ב np.sqrt ואז אין צורך בספריית math

2024-04-11 09:05 UTC, idonahum1 commented on galwa/fields.py
> +    def _find_all_dividers_of_field_size(self):
המקום היותר מתאים לפונקציה כללית כזאת היא דווקא ב utils.py, אתה יכול להשאיר את הפונקציה הנוכחית וממנה לקרוא לפונקציית find_divisors שתיהיה בתוך utils

2024-04-11 09:05 UTC, idonahum1 commented on main.py
> +                open_docs()
אין צורך ב open_docs כי אנחנו מגישים את ה pdf ולא את הhtml

2024-04-11 09:05 UTC, idonahum1 commented on main.py
> +                about_us()
נראה לי מיותר לא?

2024-04-11 09:05 UTC, idonahum1 commented on main.py
באופן כללי אתה חושב שכדאי לחשוף אותם לtests שלנו? לא בטוח שזה רעיון טוב, גם יש השוואה עם galois, אולי כדאי להמנע מזה, בסוף הטסטים היו בשבילנו.
לdemo דווקא הייתי עושה jupyter notebook, זה יותר קריא ולא דורש ידע קודם בתכנות

2024-04-11 09:05 UTC, idonahum1 commented on galwa/elements.py
> +        return self.a == other.a and self.p == other.p
פגז

2024-04-11 19:01 UTC, assafYossef commented on main.py
אני לא כזה יודע מה זה jupyter notebook. מה אתה חושב שאפשר לעשות עם זה?

2024-04-11 19:35 UTC, assafYossef commented on docs/_build/doctrees/galwa.doctree
הורדתי

2024-04-11 19:35 UTC, assafYossef commented on galwa/fields.py
> +        for i in range(1, int(math.sqrt(field_size)) + 1):
החלפתי

2024-04-11 19:36 UTC, assafYossef commented on galwa/fields.py
> +    def _find_all_dividers_of_field_size(self):
החלפתי

2024-04-11 19:37 UTC, assafYossef commented on main.py
> +                open_docs()
סבבה אני אוריד את זה אחרי שהכל מבחינתך תקין (כל הערות למעלה) כי אני פשוט ימחק את הקובץ main

2024-04-11 19:37 UTC, assafYossef commented on main.py
> +                about_us()
סבבה אני אוריד את זה אחרי שהכל מבחינתך תקין (כל הערות למעלה) כי אני פשוט ימחק את הקובץ main

2024-04-11 20:47 UTC, idonahum1 approved these changes
על הכיפאק, רשמתי הערה אחת נוספת :) 
כל הכבוד!

2024-04-11 20:47 UTC, idonahum1 commented on galwa/utils.py
> +def find_all_dividers_of_field_size(field):
מצוין, אבל בגלל שזה utils הכוונה שלי שזה צריך לקבל integer ולא field, זאת אומרת שבfinitefield אתה קורה לפונקציה הכללית הזאת שמוצאת את כל המחלקים של מספר כלשהוא, ללא קשר להאם מדובר בfield או לא

2024-04-12 09:03 UTC, idonahum1 approved these changes

2024-04-12 09:27 UTC, merged